//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatFiles.Scrutinizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlatFiles.Scrutinizer.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered a null when assigning to the non-nullable property &apos;{0}&apos;..
        /// </summary>
        public static string AssignNullToStruct {
            get {
                return ResourceManager.GetString("AssignNullToStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property selector did not select a property..
        /// </summary>
        public static string BadPropertySelector {
            get {
                return ResourceManager.GetString("BadPropertySelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to define a column with a null or blank name..
        /// </summary>
        public static string BlankColumnName {
            get {
                return ResourceManager.GetString("BlankColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to add a column to a schema where the same name already exists..
        /// </summary>
        public static string DuplicateColumnName {
            get {
                return ResourceManager.GetString("DuplicateColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record separator cannot be null or empty..
        /// </summary>
        public static string EmptyRecordSeparator {
            get {
                return ResourceManager.GetString("EmptyRecordSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column separator cannot be null or empty..
        /// </summary>
        public static string EmptySeparator {
            get {
                return ResourceManager.GetString("EmptySeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record did not meet the length requirements specified in the schema. Record {0}..
        /// </summary>
        public static string FixedLengthRecordTooShort {
            get {
                return ResourceManager.GetString("FixedLengthRecordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an invalid fixed width column alignment..
        /// </summary>
        public static string InvalidAlignment {
            get {
                return ResourceManager.GetString("InvalidAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert &apos;{0}&apos; to &apos;{1}&apos;. Column: {2}.
        /// </summary>
        public static string InvalidColumnConversion {
            get {
                return ResourceManager.GetString("InvalidColumnConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to define a column with a negative width..
        /// </summary>
        public static string InvalidColumnWidth {
            get {
                return ResourceManager.GetString("InvalidColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record did not meet the length requirements specified in the schema. Expected length is {0} but actual length is {1}..
        /// </summary>
        public static string InvalidLengthError {
            get {
                return ResourceManager.GetString("InvalidLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an invalid conversion while processing the record. Record {0}..
        /// </summary>
        public static string InvalidRecordConversion {
            get {
                return ResourceManager.GetString("InvalidRecordConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an invalid record format. Record {0}..
        /// </summary>
        public static string InvalidRecordFormatNumber {
            get {
                return ResourceManager.GetString("InvalidRecordFormatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an invalid overflow truncation policy..
        /// </summary>
        public static string InvalidTruncationPolicy {
            get {
                return ResourceManager.GetString("InvalidTruncationPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type you are trying to map does not have a default constructor..
        /// </summary>
        public static string NoDefaultConstructor {
            get {
                return ResourceManager.GetString("NoDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to view values was made after all of the records were read..
        /// </summary>
        public static string NoMoreRecords {
            get {
                return ResourceManager.GetString("NoMoreRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type provided is not a an enumeration type..
        /// </summary>
        public static string NotEnumType {
            get {
                return ResourceManager.GetString("NotEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to work with a parser after an invalid record was encountered..
        /// </summary>
        public static string ReadingWithErrors {
            get {
                return ResourceManager.GetString("ReadingWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to view values was made before reading the first record..
        /// </summary>
        public static string ReadNotCalled {
            get {
                return ResourceManager.GetString("ReadNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read values into the {0} property because it is read-only..
        /// </summary>
        public static string ReadOnlyProperty {
            get {
                return ResourceManager.GetString("ReadOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column and record separator are the same string..
        /// </summary>
        public static string SameSeparator {
            get {
                return ResourceManager.GetString("SameSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while parsing the schema {0}..
        /// </summary>
        public static string SchemaError {
            get {
                return ResourceManager.GetString("SchemaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to retrieve the schema when none was extracted or provided..
        /// </summary>
        public static string SchemaNotDefined {
            get {
                return ResourceManager.GetString("SchemaNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record did not have the number of columns specified in the schema. Expected column count is {0} but actual column count is {1}..
        /// </summary>
        public static string SeparatedValueRecordWrongColumnCount {
            get {
                return ResourceManager.GetString("SeparatedValueRecordWrongColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record did not have the number of columns specified in the schema. Record {0}..
        /// </summary>
        public static string SeparatedValueRecordWrongNumberOfColumns {
            get {
                return ResourceManager.GetString("SeparatedValueRecordWrongNumberOfColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A syntax error was encountered: Unmatched quote..
        /// </summary>
        public static string UnmatchedQuote {
            get {
                return ResourceManager.GetString("UnmatchedQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write values from the {0} property because it is write-only..
        /// </summary>
        public static string WriteOnlyProperty {
            get {
                return ResourceManager.GetString("WriteOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wrong number of values were passed..
        /// </summary>
        public static string WrongNumberOfValues {
            get {
                return ResourceManager.GetString("WrongNumberOfValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual property type did not match the indicated type..
        /// </summary>
        public static string WrongPropertyType {
            get {
                return ResourceManager.GetString("WrongPropertyType", resourceCulture);
            }
        }
    }
}
